### ISSUE TITLE
Download databases issue

### ISSUE THREAD

**Issue by imanyass** [bacpop/ggCaller#20] opened 2023-12-21 17:04 UTC
Hello, I hope you're well. I followed the recommended procedure to install ggcaller from the source. However, upon attempting to run ggcaller, I encountered the following error. I've already downloaded the model database into the models directory as advised in previous issues, but the error persists. Could you please assist me with resolving this? Thank you in advance.

Building coloured compacted DBG...
Generating graph stop codon index...
Mapping contigs to graph...
Downloading databases...
Traceback (most recent call last):
  File "conda/envs/ggcaller/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "conda/envs/ggcaller/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "conda/envs/ggcaller/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "conda/envs/ggcaller/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "conda/envs/ggcaller/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "conda/envs/ggcaller/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "conda/envs/ggcaller/lib/python3.9/http/client.py", line 1447, in connect
    super().connect()
  File "conda/envs/ggcaller/lib/python3.9/http/client.py", line 946, in connect
    self.sock = self._create_connection(
  File "conda/envs/ggcaller/lib/python3.9/socket.py", line 844, in create_connection
    raise err
  File "conda/envs/ggcaller/lib/python3.9/socket.py", line 832, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "conda/envs/ggcaller/bin/ggcaller", line 33, in <module>
    sys.exit(load_entry_point('ggCaller==1.3.4', 'console_scripts', 'ggcaller')())
  File "conda/envs/ggcaller/lib/python3.9/site-packages/ggCaller-1.3.4-py3.9-linux-x86_64.egg/ggCaller/__main__.py", line 436, in main
    db_dir = download_db()
  File "conda/envs/ggcaller/lib/python3.9/site-packages/ggCaller-1.3.4-py3.9-linux-x86_64.egg/models/__main__.py", line 15, in download_db
    filename = wget.download(url, out=module_dir)
  File "conda/envs/ggcaller/lib/python3.9/site-packages/wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "conda/envs/ggcaller/lib/python3.9/urllib/request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "conda/envs/ggcaller/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "conda/envs/ggcaller/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "conda/envs/ggcaller/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "conda/envs/ggcaller/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "conda/envs/ggcaller/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "conda/envs/ggcaller/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
srun: error: compf008: task 0: Exited with exit code 1

**Comment by samhorsfield96** [comment] 2024-01-03 09:47
Hi, sorry to hear you ran into this issue. This has been encountered before, please see here: https://github.com/bacpop/ggCaller/issues/16#issuecomment-1828314000

**Comment by samhorsfield96** [comment] 2024-01-09 11:39
Closed as repeated issue.

**Comment by imanyass** [comment] 2024-01-09 11:43
Hi, thanks for your message. Although I downloaded the database as recommended I'm still encountering the same problem. Any advice?

**Comment by samhorsfield96** [comment] 2024-01-09 15:23
Hi, what was the error message? Also, which directory did you place the database file in?

**Comment by imanyass** [comment] 2024-01-10 10:46
Hi, thanks for your message. I placed the database file in the models directory but when I run ggcaller I'm still having the same error 
Building coloured compacted DBG...
Generating graph stop codon index...
Mapping contigs to graph...
Downloading databases...
Traceback (most recent call last):
File "conda/envs/ggcaller/lib/python3.9/urllib/request.py", line 1346, in do_open
h.request(req.get_method(), req.selector, req.data, headers,
File "conda/envs/ggcaller/lib/python3.9/http/client.py", line 1285, in request
self._send_request(method, url, body, headers, encode_chunked)
File "conda/envs/ggcaller/lib/python3.9/http/client.py", line 1331, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "conda/envs/ggcaller/lib/python3.9/http/client.py", line 1280, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "conda/envs/ggcaller/lib/python3.9/http/client.py", line 1040, in _send_output
self.send(msg)
File "conda/envs/ggcaller/lib/python3.9/http/client.py", line 980, in send
self.connect()
File "conda/envs/ggcaller/lib/python3.9/http/client.py", line 1447, in connect
super().connect()
File "conda/envs/ggcaller/lib/python3.9/http/client.py", line 946, in connect
self.sock = self._create_connection(
File "conda/envs/ggcaller/lib/python3.9/socket.py", line 844, in create_connection
raise err
File "conda/envs/ggcaller/lib/python3.9/socket.py", line 832, in create_connection
sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "conda/envs/ggcaller/bin/ggcaller", line 33, in
sys.exit(load_entry_point('ggCaller==1.3.4', 'console_scripts', 'ggcaller')())
File "conda/envs/ggcaller/lib/python3.9/site-packages/ggCaller-1.3.4-py3.9-linux-x86_64.egg/ggCaller/main.py", line 436, in main
db_dir = download_db()
File "conda/envs/ggcaller/lib/python3.9/site-packages/ggCaller-1.3.4-py3.9-linux-x86_64.egg/models/main.py", line 15, in download_db
filename = wget.download(url, out=module_dir)
File "conda/envs/ggcaller/lib/python3.9/site-packages/wget.py", line 526, in download
(tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
File "conda/envs/ggcaller/lib/python3.9/urllib/request.py", line 239, in urlretrieve
with contextlib.closing(urlopen(url, data)) as fp:
File "conda/envs/ggcaller/lib/python3.9/urllib/request.py", line 214, in urlopen
return opener.open(url, data, timeout)
File "conda/envs/ggcaller/lib/python3.9/urllib/request.py", line 517, in open
response = self._open(req, data)
File "conda/envs/ggcaller/lib/python3.9/urllib/request.py", line 534, in _open
result = self._call_chain(self.handle_open, protocol, protocol +
File "conda/envs/ggcaller/lib/python3.9/urllib/request.py", line 494, in _call_chain
result = func(*args)
File "conda/envs/ggcaller/lib/python3.9/urllib/request.py", line 1389, in https_open
return self.do_open(http.client.HTTPSConnection, req,
File "conda/envs/ggcaller/lib/python3.9/urllib/request.py", line 1349, in do_open
raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
srun: error: compa016: task 0: Exited with exit code 1

my command-line is srun ggcaller --refs FastaFiles.ls
The models directory includes
 __init__.py  
__main__.py  
ggCallerdb.tar.bz2

Is there any option that I should specify to use the downloaded database?

**Comment by samhorsfield96** [comment] 2024-01-10 11:35
Hi, I believe the issue is that the databases file is not being copied to the ggcaller conda lib directory. Please navigate to the source ggCaller directory and try running with `python ggcaller-runner.py --refs /path/to/FastaFiles.ls`

**Comment by imanyass** [comment] 2024-01-11 13:05
Hello, it is working! Thanks for your help.

**Comment by samhorsfield96** [comment] 2024-01-12 12:19
Closed as completed.

**Closed by samhorsfield96** 2024-01-12 12:19 UTC
